languageCode = "en-us"
title = "Jonathan Keane Photography"
# Supposedly: if specified, it messes up some links on the preview site, is it needed at all?
baseURL = "https://photo.jonkeane.com"
googleanalytics = "G-CPQDC0642Z"
# disableKinds = ["taxonomy", "section"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
timeout = 600

[params]
  description = "Travelling the world and taking photographs of things that catch my eye. Landscapes, cityscapes, nature, people."
  images = ["photo-jonkeane.jpg"]
  title = "Jonathan Keane Photography"
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  dateFormat = "2006-01-02"
  emulsions = [
      'Cat Labs',
      'Fuji Pro 400H',
      'Fujifilm Pro 400H',
      'Fujifilm Pro H',
      'Fuji Provia',
      'Fujifilm Provia F',
      'Fujifilm Provia',
      'Fuji Velvia',
      'Fujifilm Velvia',
      'Ilford Delta',
      'Kodak E100',
      'Kodak Ektachrome E100',
      'Kodak Ektachrome E',
      'Kodak Ektar 100',
      'Kodak Ektar',
      'Kodak Gold 200',
      'Kodak Gold',
      'Kodak Portra 160',
      'Kodak Portra 400',
      'Kodak Portra 800',
      'Kodak Portra',
      'Kodak T-Max 100',
      'Kodak T-Max',
      'Kentmere PAN 400',
      'CatLABS X FILM 100',
      'Fujifilm Fujichrome Velvia 50',
      'Fujifilm Fujichrome Provia 100F',
      'Fujifilm Fujicolor Pro 400H',
      'Kentmere PAN 100',
      'CatLABS 100'
  ]


[module]
[[module.mounts]]
    source = "static/assets"
    target = "assets"
[[module.mounts]]
    source = "assets"
    target = "assets"
[[module.imports]]
    path = "github.com/curtiscde/hugo-theme-massively"


# If adding any taxonomies here, also need to add to layout/_default/taxonomy.html
[taxonomies]
  camera = "cameras"
  lens = "lenses"
  emulsion = "emulsions"
  tag = "tags"

[params.slider]
    enable = true

[params.meta]
   keywords = "photography, photographs, photos, prints, art, framed prints, travel, landscapes, cityscapes, nature, japan, chicago, australia"
   description = "Travelling the world and taking photographs of things that catch my eye. Landscapes, cityscapes, nature, people."
   robots = "index, follow, noarchive"
   googlebot = "noarchive"
   googlesiteverification = "f2zJ8lbq0tyR9J_pME6DbTDQWFrLLH-m98SKSbgnmCE"

[imaging.exif]
  includeFields = "Description"

[params.posts]
  featuredPost = false
  pageSize = "25"

[params.galleries]
  featuredPost = false
  pageSize = "10"

# Below parameters can be set to override default post settings
# [params.posts]
#   featuredPost = false
#     folderName = "post"
#     pageSize = "6"
#     paginationPages = 2
#     showFirstLast = false

[languages]
[languages.en]
  languageName = "English"
#[languages.es]
#  languageName = "Español"
#  title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
